In [1]:
import torch

In [2]:
m = torch.nn.Identity()
input = torch.randn(128, 20)
print(f"Input: {input}")
print()
output = m(input)
print(f"Output: {input}")
print(output.size())
torch.Size([128, 20])

Input: tensor([[ 0.6301,  0.9311,  1.5616,  ..., -1.4857, -0.0526, -0.4488],
        [ 0.7230,  0.0365, -0.1017,  ..., -1.1195,  0.1788, -0.1635],
        [ 0.1464, -0.7547,  1.7467,  ...,  1.6025,  0.2689,  0.2347],
        ...,
        [ 1.0643,  1.2201,  1.7154,  ..., -0.1849,  1.3714, -0.5509],
        [ 0.1265, -0.3147, -0.8087,  ..., -1.1544,  0.1203, -0.9606],
        [ 0.7078, -0.1613, -2.4266,  ...,  1.5252,  0.1467, -1.8010]])

Output: tensor([[ 0.6301,  0.9311,  1.5616,  ..., -1.4857, -0.0526, -0.4488],
        [ 0.7230,  0.0365, -0.1017,  ..., -1.1195,  0.1788, -0.1635],
        [ 0.1464, -0.7547,  1.7467,  ...,  1.6025,  0.2689,  0.2347],
        ...,
        [ 1.0643,  1.2201,  1.7154,  ..., -0.1849,  1.3714, -0.5509],
        [ 0.1265, -0.3147, -0.8087,  ..., -1.1544,  0.1203, -0.9606],
        [ 0.7078, -0.1613, -2.4266,  ...,  1.5252,  0.1467, -1.8010]])
torch.Size([128, 20])


torch.Size([128, 20])

In [3]:
input.sum().absolute()

tensor(79.3932)

In [4]:
y_fool = torch.tensor([3,2,3])
y_fool

tensor([3, 2, 3])

In [5]:
y_fool = y_fool.unsqueeze(1)
y_fool

tensor([[3],
        [2],
        [3]])

In [6]:
y_fool = torch.cat((y_fool, torch.tensor([3,4,5]).unsqueeze(1)), 1)
y_fool = torch.cat((y_fool, torch.tensor([1,2,3]).unsqueeze(1)), 1)
y_fool = torch.cat((y_fool, torch.tensor([1,2,3]).unsqueeze(1)), 1)
y_fool

tensor([[3, 3, 1, 1],
        [2, 4, 2, 2],
        [3, 5, 3, 3]])

In [7]:
y_poll, _ = torch.mode(y_fool, dim=1)
y_poll.cpu()

tensor([1, 2, 3])

In [9]:
threshold = -13.0000

In [96]:
scores = torch.tensor([[-25.3880, -11.3583],
        [-22.2457, -11.0157],
        [-21.2706, -13.6260],
        [-25.3501, -15.3649],
        [-19.2668, -10.4720],
        [ -9.1738, -21.5336],
        [-24.6928, -14.1541],
        [-20.4336,  -9.0227],
        [ -9.9925, -21.4996],
        [ -9.4385, -20.3439],
        [ -9.8624, -21.6132],
        [-11.9485, -21.0638],
        [ -9.5145, -20.6907],
        [-13.0642, -20.6096],
        [ -7.8694, -20.3417],
        [-11.2971, -19.8578]])

In [97]:
scores

tensor([[-25.3880, -11.3583],
        [-22.2457, -11.0157],
        [-21.2706, -13.6260],
        [-25.3501, -15.3649],
        [-19.2668, -10.4720],
        [ -9.1738, -21.5336],
        [-24.6928, -14.1541],
        [-20.4336,  -9.0227],
        [ -9.9925, -21.4996],
        [ -9.4385, -20.3439],
        [ -9.8624, -21.6132],
        [-11.9485, -21.0638],
        [ -9.5145, -20.6907],
        [-13.0642, -20.6096],
        [ -7.8694, -20.3417],
        [-11.2971, -19.8578]])

In [98]:
for index, score in enumerate(scores):
    if score[1] > score[0]:
        print(index, score[1])

0 tensor(-11.3583)
1 tensor(-11.0157)
2 tensor(-13.6260)
3 tensor(-15.3649)
4 tensor(-10.4720)
6 tensor(-14.1541)
7 tensor(-9.0227)


In [105]:
new_scores = None
for index, score in enumerate(scores):
    # print(index)
    if score[1] > score[0]:
        new_score = torch.tensor([score[0] + threshold, score[1] + -threshold ])

    else:
        new_score = torch.tensor([score[0] + -threshold, score[1] + threshold])

    if new_scores is None:
        new_scores = new_score.unsqueeze(0)        
    else:
        new_scores = torch.cat((new_scores, new_score.unsqueeze(0)),0)

new_scores

tensor([[-38.3880,   1.6417],
        [-35.2457,   1.9843],
        [-34.2706,  -0.6260],
        [-38.3501,  -2.3649],
        [-32.2668,   2.5280],
        [  3.8262, -34.5336],
        [-37.6928,  -1.1541],
        [-33.4336,   3.9773],
        [  3.0075, -34.4996],
        [  3.5615, -33.3439],
        [  3.1376, -34.6132],
        [  1.0515, -34.0638],
        [  3.4855, -33.6907],
        [ -0.0642, -33.6096],
        [  5.1306, -33.3417],
        [  1.7029, -32.8578]])

In [104]:
for index, score in enumerate(new_scores):
    if score[1] > score[0]:
        print(index, score[1])

0 tensor(1.6417)
1 tensor(1.9843)
2 tensor(-0.6260)
3 tensor(-2.3649)
4 tensor(2.5280)
6 tensor(-1.1541)
7 tensor(3.9773)


In [51]:
torch.max(subtracted_scores,1)

torch.return_types.max(
values=tensor([ 1.6417,  1.9843, -0.6260, -2.3649,  2.5280,  3.8262, -1.1541,  3.9773,
         3.0075,  3.5615,  3.1376,  1.0515,  3.4855, -0.0642,  5.1306,  1.7029]),
indices=tensor([1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]))

In [48]:
values, indices =torch.max(scores, 1)

values, indices

(tensor([-11.3583, -11.0157, -13.6260, -15.3649, -10.4720,  -9.1738, -14.1541,
          -9.0227,  -9.9925,  -9.4385,  -9.8624, -11.9485,  -9.5145, -13.0642,
          -7.8694, -11.2971]),
 tensor([1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]))

In [45]:
bool_preds = ( (indices == 1) & (values > -13.0000) )
bool_preds.int()

tensor([1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.int32)

In [46]:
( (indices == 1) & (values > -13.0000) ).long()

tensor([1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0])